Access control
devonfw-sample/devon4quarkus-reference pull request #38
Opened 2021-12-21 13:04 UTC by GuentherJulian

Closes https://github.com/devonfw-sample/devon4quarkus-reference/issues/27
* Added Smallrye JWT extension
* Adapted tests
* Added documentation on how to deploy and configure keycloak

2021-12-21 13:20 UTC, rafaelvicariabarker requested changes
Made some language suggestions

2021-12-21 13:20 UTC, rafaelvicariabarker commented on documentation/Keycloak/keycloak_authentication.asciidoc
> +You can access Keycloak by browsing to http://localhost:8180/auth/ in your browser. Open the Administration console and log in with the default username "admin" and password "admin".
by **navigating** to ... in your browser

2021-12-21 13:20 UTC, rafaelvicariabarker commented on documentation/Keycloak/keycloak_authentication.asciidoc
> +After this, open the "Credentials" tab and enter the credentials for the user. The newly created user is now able to authenticate himself in Keycloak. By default, new users must enter a new password
...enter the credentials **of** the user

2021-12-21 13:20 UTC, rafaelvicariabarker commented on documentation/Keycloak/keycloak_authentication.asciidoc
> +Finally we can again test the delete method. Pass the "access_token" from the previous response as Bearer token in the Authorization header of the request.
Finally, we can test the delete method **again**.

2021-12-21 13:37 UTC, rafaelvicariabarker approved these changes

2021-12-27 13:20 UTC, maybeec commented
@GuentherJulian please check the credentials and please redo a clean PR. There are private keys  here as part of the PR.
Not sure where they come from. But we have to be careful to not have any passwords and private keys in Git if possible although if they are just for "testing" as it will ring alarms at different ends as well and we'll get contacted to clarify such things as there is always the risk that we will oversee some critical occurrences for sure.

2021-12-27 13:20 UTC, closed without merging

2021-12-27 14:06 UTC, rafaelvicariabarker requested changes